### ISSUE TITLE
Ten years reproducibility challenge: **Paper number**: 39

### ISSUE THREAD

**Issue by alegrand** [ReScience/ten-years#12]
**Paper number**: 39

**Original article:** Pedro Velho and Arnaud Legrand, Accuracy Study and Improvement of Network Simulation in the SimGrid Framework. (2009) SIMUTools'09, 2nd International Conference on Simulation Tools and Techniques, Mar 2009, Rome, Italy. 
**Article age**: 10 years old

**Open access version**: https://hal.inria.fr/inria-00361031/file/simutools09.pdf

**PDF URL:** https://github.com/alegrand/reproducibility-challenge/blob/master/article.pdf
**Metadata URL:**
**Code URL:** https://github.com/alegrand/reproducibility-challenge

**Scientific domain:** Computer Science, Distributed Systems
**Programming language:** C/C++
**Suggested editor:** @khinsen

_Originally posted by @alegrand in https://github.com/ReScience/ten-years/issues/1#issuecomment-587930696_

**Comment by rougier** [comment]
Hi @alegrand, Can you post your submission from https://github.com/rescience/submissions/issues/new/choose (and pick reproduction)?

**Comment by alegrand** [comment]
Oh, sorry about this. I was not completely clear about the submission procedure. Here is the new submission: https://github.com/ReScience/submissions/issues/39 Thanks a lot!
