### ISSUE TITLE
Long-term availability and consistency of 3D macromolecular structure data in the wwPDB

### ISSUE THREAD

**Issue by jdwestbrook** [ReScience/ten-years#7]
This article below describes wwPDB efforts to provide FAIR 3D macromolecular structure data.  
This issue will focus on a fundamental requirement for computational reproducibility, the long-term availability and consistency of key archival data repositories. 

Henrick K, Feng Z, Bluhm WF, Dimitropoulos D, Doreleijers JF, Dutta S, Flippen-Anderson JL, Ionides J, Kamada C, Krissinel E, Lawson CL, Markley JL, Nakamura H, Newman R, Shimizu Y, Swaminathan J, Velankar S, Ory J, Ulrich EL, Vranken W, Westbrook J, Yamashita R, Yang H, Young J, Yousufuddin M, Berman HM. Remediation of the protein data bank archive. Nucleic Acids Res. 2008 Jan;36(Database issue):D426-33. doi: 10.1093/nar/gkm937. Epub 2007 Dec 11. PMID: 18073189; PMCID: PMC2238854.

**Comment by rougier** [comment]
Hi @jdwestbrook,

Thanks for your future participation in the challenge. The issue for [declaration of participation](https://github.com/ReScience/ten-years/issues/1) is #1. Could you repost your message in that issue?
